update fun Bai10
nguyenduykhanh1025/ExerciseJava pull request #4
Opened 2019-05-15 09:34 UTC by nguyenduykhanh1025

2019-05-15 10:25 UTC, voquanghoa commented on src/main/java/Bai12.java
> +       return df.format(p);
Dùng String.format nhanh hơn

2019-05-15 10:25 UTC, voquanghoa commented on src/test/java/Bai12Test.java
> +        assertEquals(new Bai12().getResurt(3), "2.66667");
Thêm test case với n lớn hơn. 
Add test case cho hàm  `layGiaThua`

2019-05-15 10:25 UTC, voquanghoa commented on src/test/java/Bai12Test.java
> +    @Test
Thiếu dòng trống

2019-05-15 10:25 UTC, voquanghoa commented on src/test/java/Bai12Test.java
> +    public void test_getResurt() {
Sai chính tả

2019-05-15 10:25 UTC, voquanghoa commented on src/main/java/Bai12.java
> +    public String getResurt(int n) {
Sai chính tả

2019-05-15 10:25 UTC, voquanghoa commented on src/main/java/Bai12.java
> +        double p = 0.0;
Tab có vấn đề

2019-05-15 10:25 UTC, voquanghoa commented on src/main/java/Bai12.java
> +           p += (1.0/layGiaThua(i));
Dư dấu ngoặc ()

2019-05-15 10:25 UTC, voquanghoa commented on src/main/java/Bai12.java
> +            p*=i;
Thiếu khoảng trống `p *= i;`

2019-05-15 10:25 UTC, voquanghoa commented on src/main/java/Bai12.java
> +import org.omg.PortableInterceptor.SYSTEM_EXCEPTION;
Dư phép import

2019-05-15 10:25 UTC, voquanghoa commented on src/test/java/Bai12Test.java
> +public class Bai12Test {
Để 1 dòng trống giữa import với khai báo class

2019-05-15 10:26 UTC, voquanghoa commented
Tại sao tên branch là Basics-exercise-11 nhưng lại làm bài 12?

2019-05-19 08:04 UTC, nguyenduykhanh1025 commented on src/main/java/Bai12.java
> +       return df.format(p);
done

2019-05-19 08:06 UTC, nguyenduykhanh1025 commented on src/test/java/Bai12Test.java
> +        assertEquals(new Bai12().getResurt(3), "2.66667");
với hàm lấy giai thừa thì có thể cho giá trị lớn. Nhưng em đang bị vấn đề là nếu lấy giá trị giai thừa lớn quá thì phép chia của 1/(số lớn) nó không thực hiện được.

2019-05-19 08:06 UTC, nguyenduykhanh1025 commented on src/test/java/Bai12Test.java
> +    @Test
done

2019-05-19 08:06 UTC, nguyenduykhanh1025 commented on src/test/java/Bai12Test.java
> +    public void test_getResurt() {
done

2019-05-19 08:06 UTC, nguyenduykhanh1025 commented on src/main/java/Bai12.java
> +    public String getResurt(int n) {
done

2019-05-19 08:06 UTC, nguyenduykhanh1025 commented on src/main/java/Bai12.java
> +        double p = 0.0;
done

2019-05-19 08:06 UTC, nguyenduykhanh1025 commented on src/main/java/Bai12.java
> +           p += (1.0/layGiaThua(i));
done

2019-05-19 08:07 UTC, nguyenduykhanh1025 commented on src/main/java/Bai12.java
> +            p*=i;
done

2019-05-19 08:07 UTC, nguyenduykhanh1025 commented on src/main/java/Bai12.java
> +import org.omg.PortableInterceptor.SYSTEM_EXCEPTION;
done

2019-05-19 08:07 UTC, nguyenduykhanh1025 commented on src/test/java/Bai12Test.java
> +public class Bai12Test {
done

2019-05-20 15:33 UTC, voquanghoa requested changes

2019-05-20 15:33 UTC, voquanghoa commented on src/main/java/Bai12.java
> +            p += 1.0 / layGiaThua(i).longValue();
Hàm layGiaiThua dùng kiểu BigInteger để tính số lớn nhưng ngay sau đó lại lấy longValue là vô nghĩa

2019-05-20 15:33 UTC, voquanghoa commented on src/main/java/Bai12.java
> +            p += 1.0 / layGiaThua(i).longValue();
Cố gắng tính toán mà không dùng giai thừa

2019-05-20 15:33 UTC, voquanghoa commented on src/main/java/Bai12.java
> +        return String.format("%.5f", p);
Phải trả về double

2019-05-20 15:33 UTC, voquanghoa commented on src/main/java/Bai12.java
> +            BigInteger index = new BigInteger(String.format("%d", i));
Dùng valueOf

2019-05-30 05:10 UTC, closed without merging